# Generated by Django 6.1.1 on 2026-10-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='currency_code',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='currency_name',
            field=models.CharField(default='Indian Rupee', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='currency_symbol',
            field=models.CharField(default='₹', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='date_format',
            field=models.CharField(default='DD/MM/YYYY', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='financial_year_start',
            field=models.CharField(default='04-01', help_text='MM-DD format (April 1st)', max_length=5),
        ),
        migrations.AddField(
            model_name='company',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=50),
        ),
    ]
