# Django REST Framework serializers
from rest_framework import serializers

# Import CRM models
from .models import Contact, Lead


# Serializer for Contact model
class ContactSerializer(serializers.ModelSerializer):

    # Show company name instead of only company ID
    company_name = serializers.CharField(
        source="company.name",
        read_only=True,
    )

    # Show owner's username
    owner_username = serializers.CharField(
        source="owner.username",
        read_only=True,
    )

    class Meta:
        model = Contact

        fields = [
            "id",
            "company",
            "company_name",
            "owner",
            "owner_username",
            "first_name",
            "last_name",
            "email",
            "phone",
            "designation",
            "department",
            "is_active",
            "created_at",
        ]

        # These fields are generated by the backend
        read_only_fields = [
            "id",
            "company_name",
            "owner_username",
            "created_at",
        ]


# Serializer for Lead model
class LeadSerializer(serializers.ModelSerializer):

    # Show company name in the API response
    company_name = serializers.CharField(
        source="company.name",
        read_only=True,
    )

    # Show owner's username in the API response
    owner_username = serializers.CharField(
        source="owner.username",
        read_only=True,
    )

    class Meta:
        model = Lead

        fields = [
            "id",
            "company",
            "company_name",
            "owner",
            "owner_username",
            "first_name",
            "last_name",
            "email",
            "phone",
            "source",
            "status",
            "notes",
            "is_active",
            "created_at",
        ]

        # These fields should not be manually supplied
        read_only_fields = [
            "id",
            "company_name",
            "owner_username",
            "created_at",
        ]