# Generated by Django 6.1.1 on 2026-09-26 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_is_active'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('contract', 'Contract'), ('nda', 'NDA'), ('invoice', 'Invoice'), ('quotation', 'Quotation'), ('employee', 'Employee'), ('financial', 'Financial'), ('other', 'Other')], db_index=True, default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company', 'category'], name='documents_d_company_501eb2_idx'),
        ),
    ]
