# Generated by Django 6.1.1 on 2026-09-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_purchaseinvoice_purchaseinvoiceitem_purchasepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='vendor_invoice_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
